<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
			<?php
				if(isset($title)){
					echo "$title--逝去";
				} else {
					echo "clkTest";
				}
			?>
		</title>
		<script type="text/javascript" src="/assets/js/p.js"></script>
		<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
		<script type="text/javascript" src="//cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
		<script type="text/javascript" src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="//cdn.bootcss.com/layer/2.3/layer.js"></script>
		{% block style %}{%endblock %}
	</head>
<body>
	{% block body %}{% endblock %}	
</body>
	{% block script %}{% endblock %}
</html>