{% extends "templates/base2.phtml" %}
{% block body %}
	<nav  class="navbar navbar-default">
		<div class="container-fluid">	
			<nav class="collapse navbar-collapse bs-navbar-collapse">
				<div class="pull-left"> 
					<span class="navbar-brand">陈龙科 - 瞎搞的个人网站</span> 
				</div>

				<ul class="nav navbar-nav pull-left">
					<li class="active"><a href="javascript:void(0);">主页</a></li>
					<li><a href="javascript:void(0);">测试页一</a></li>
					<li><a href="javascript:void(0);">测试页二</a></li>
					<li class="dropdown">
          				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">下拉框 <span class="caret"></span></a>
      					<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>
        			</li>
				</ul>

				<div class="navbar-header pull-right">
					<span class="navbar-brand">{{_nick}}</span>
			      	<a class="navbar-brand" href="/login/logout" title="退出"> <span class="glyphicon glyphicon glyphicon-off" aria-hidden="true"></span></a>
			    </div>
			</nav>
		</div>
	</nav>

	<div class="container">
		<img title="Adorable" class="lazy" alt="Adorable" data-original="/assets/img/wanzi/la la la.gif" width="120" height="120">
    	<img title="Adorable" class="lazy" alt="Adorable" data-original="/assets/img/wanzi/Strive.gif" width="120" height="120">
    	<img title="Adorable" class="lazy" alt="Adorable" data-original="/assets/img/wanzi/Adorable.gif" width="120" height="120">    	
    	<div>
    		<button class="btn">按扭</button>
    	</div>
	</div>
{% endblock %}
{% block script %}
<script type="text/javascript" src="//apps.bdimg.com/libs/jquery-lazyload/1.9.5/jquery.lazyload.min.js"></script>
<script type="text/javascript">
	$("img.lazy").lazyload({effect: "fadeIn"});
</script>
{% endblock %}