<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
        <title>测试</title>
    </head>
    <body>
        <a href="itms-services://?action=download-manifest&url=https://test.odamiao.com/qianniu.plist">点我试试看</a>
        <!-- //https://test.odamiao.com/JDY-Debug-3.8.ipa -->
    </body>
</html>